Refactor department queries
equinor/fusion-app-resources pull request #336
Opened 2021-06-10 14:37 UTC by loldot

- [x] New feature
- [ ] Bug fix
- [ ] High impact

**Description of work:**
Refactor department queries for readability and use cases

**Testing:**
- [x] Can be tested
- [x] Automatic tests created / updated
- [x] Local tests are passing

**Checklist:**
- [x] Considered automated tests
- [x] Considered updating specification / documentation
- [x] Considered work items 
- [x] Considered security
- [x] Performed developer testing
- [x] Checklist finalized / ready for review

2021-06-17 12:40 UTC, xssic requested changes
Not sure why you introduced DbContext in the controller, but I don't think it is the right way...

2021-06-17 12:40 UTC, xssic commented on src/backend/api/Fusion.Resources.Api/Controllers/Departments/DepartmentsController.cs
> +        private readonly ResourcesDbContext db;
Don't think you should introduce db context here.
Should use query handler instead.

2021-06-18 04:37 UTC, HansDahle approved these changes

2021-06-18 06:06 UTC, xssic approved these changes

2021-06-18 06:46 UTC, merged